spring:
  config:
    activate:
      on-profile: dev
  application:
    name: w08e-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.140.221.15:3307/xiaomai?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: '1+1=0o.o0'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
  data:
    redis:
      host: 43.140.221.15
      port: 6379
      database: 0


server:
  port: 9999
#sa-token:
#  token-name: satoken
#  timeout: 2592000
#  active-timeout: -1
#  is-concurrent: true
#  is-share: true
#  token-style: uuid
#  is-log: true


logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

  # 开发者应该设置成自己的wx相关信息
xiaomai:
  wx:
    appid: wx9332ff959618beb1
    secret: 46b14f0ae83c64fca5e1ae04d09ef566
    # 消息推送配置token
    token:
    # 消息推送配置AesKey
    aesKey:
